// <auto-generated />
namespace InzSklep.Migrations.ConfigurationUsers
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitUsersMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitUsersMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201707171033391_InitUsersMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
