// <auto-generated />
namespace InzSklep.Migrations.ConfigurationStore
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editProductTablev2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editProductTablev2));
        
        string IMigrationMetadata.Id
        {
            get { return "201708081124590_editProductTablev2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
